services:
  # payload:
  #   image: oven/bun:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "bun install && bun run dev"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  postgres:
    image: postgres:17-trixie
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  # node_modules:
